### ISSUE TITLE
Crashed after auto-update

### ISSUE THREAD

**Issue by zzwxh** [Chit132/abyss-overlay#20]
title

**Comment by zzwxh** [comment]
win11 x64

**Comment by Cryptizism** [comment]
If possible can you go to the [discord](https://discord.gg/eDnHTT3aBS) so that we can gather more information more quickly, if not can you please provide more context with the matter, what Abyss Overlay you were on then and what you are on now and if the new one works.

**Comment by Cryptizism** [comment]
closed due to stale issue, if you return you are free to re-open
