### ISSUE TITLE
Doesnt work with MultiMC

### ISSUE THREAD

**Issue by ImPot8o** [Chit132/abyss-overlay#23]
No idea if this is news or not, but Abyss just doesnt register MultiMC as Minecraft. i tried typing /who or /api new, and it doesnt update in Abyss, nothing happens. I switched over to the regular launcher and tried it and it worked fine.

**Comment by Nodo08** [comment]
> No idea if this is news or not, but Abyss just doesnt register MultiMC as Minecraft. i tried typing /who or /api new, and it doesnt update in Abyss, nothing happens. I switched over to the regular launcher and tried it and it worked fine.

MultiMC installs "instances" meaning seperate folders for each installation, aka you will need to set your custom log path to the folder which you are playing MC from, and select the log file from there. That should fix your problem.

Also, we prefer doing support inside our discord server, thanks. 
discord.gg/abyssoverlay

**Comment by ImPot8o** [comment]
> > No idea if this is news or not, but Abyss just doesnt register MultiMC as Minecraft. i tried typing /who or /api new, and it doesnt update in Abyss, nothing happens. I switched over to the regular launcher and tried it and it worked fine.
> 
> MultiMC installs "instances" meaning seperate folders for each installation, aka you will need to set your custom log path to the folder which you are playing MC from, and select the log file from there. That should fix your problem.
> 
> Also, we prefer doing support inside our discord server, thanks. discord.gg/abyssoverlay

I see, thank you for the help!
