### ISSUE TITLE
Feature requestion: Non-transparent UI.

### ISSUE THREAD

**Issue by fw4hre0xxq** [Chit132/abyss-overlay#24]
I'm making this issue for a friend. He does not like how the GUI for the menu is transparent, because it's hard to read with his desktop background, and setting the opacity to 100% makes the font hard to read. He's requesting an option to make a non-transparent background in a less janky, with text easier to read.

Thanks.

**Comment by Cryptizism** [comment]
This is already planned, however, thank you for the suggestion. We will be implemented by separating background colour and text colour for readability, hopefully that will solve your issue

**Comment by Atvaster** [comment]
Maybe instead add an option to change text colors separately from background color?

**Comment by Chit132** [comment]
This was done a while ago with the color/opacity slider in settings!
