### ISSUE TITLE
Allow going back to main screen by clicking ABYSS logo

### ISSUE THREAD

**Issue by Cryptizism** [Chit132/abyss-overlay#37]
This will make it easier to get back to the main screen as many people ask how to get back to the stats page.

However, this may not be utilised, will have to get a second opinion before making PR. (4 line change PR)

**Comment by Chit132** [comment]
done in commit https://github.com/Chit132/abyss-overlay/commit/8023083dcfa374bc6a65cf8ae30fabe128b55fff
