### ISSUE TITLE
Amendments for new API changes

### ISSUE THREAD

**Issue by Cryptizism** [Chit132/abyss-overlay#38]
Hypixel has moved all their API management and generation to their new dashboard
This has many effects and requires changes in code.

- [x] Get rid of `/api new` API Key detection
- [x] Move from `key` in url parameters to `API-Key` header
- [x] Move from `/key` endpoint in the `verifyKey` function
   - [x] Ask to enter IGN
- [x] Direct users to https://developer.hypixel.net/ for API keys
   - [x] Instructions for users when they get there
- [x] Update new API ratelimit
- [x] Button to clear API key
- [ ] Key throttle numbers display
- [ ] Caching

**Comment by Chit132** [comment]
all but last 2 addressed in commit https://github.com/Chit132/abyss-overlay/commit/8023083dcfa374bc6a65cf8ae30fabe128b55fff

**Comment by Cryptizism** [comment]
@Chit132 for the rate limit stuff we gotta change from jquery ajax to quite literally anything else because of done weird CORS related bug with jquery not exposing custom response headers

**Comment by Cryptizism** [comment]
@Chit132 Imma close this issue because of the backend
