### ISSUE TITLE
there r too many nick on my overlay!!!even me!!!!

### ISSUE THREAD

**Issue by MoxuanChina** [Chit132/abyss-overlay#43]
in hypixel im a vip+ . when i use every overlay there r too many nick on it , but i think its not normall because i see im nicked! to solve this problem i restart the computer but it also doesnt work. i reinstall the lunar and overlay for many times .the result is terrible.it also doesnt work.i try many ways but it doesnt work . please help me !!!what can i do?write to me soon pls. my engish is not good.please forgive me.

**Comment by MoxuanChina** [comment]
![QQ图片20230813143856](https://github.com/Chit132/abyss-overlay/assets/142135010/e6881b26-f92d-4963-bfd4-f723a6ed5c38)

**Comment by Cryptizism** [comment]
The Mojang API current has decreased their API rate limits to something extremely low and so this occurs, we rely on the Mojang API to provide UUIDs to us, as a result this is what happens. We can't do much about this as all UUIDs come from the Mojang API

**Comment by ItzLevvie** [comment]
Distinguish players between UUID versions rather than using the Mojang API and hitting rate limits.

There's no documentation since my project is used for laby.net UUID Contributor but I have made my code open-source for other people to take a look at: https://github.com/ItzLevvie/uuids/blob/4f0d6ca00c7a64e28c2b112e1c1bdedae49222a5/launch.js

More specifically,

```javascript
[...]

// Minecraft puts all players under UUID version 4.
if (uuids[14] === "4") {
    Chat.log("§a" + players + " §fwith §a" + uuids);
    FS.open("validPlayers.txt").append(players + "\r\n");
    FS.open("validUUIDs.txt").append(uuids + "\r\n");
    FS.open("DEBUG.txt").append(players + " (player) with " + uuids + " (UUID version 4)" + "\r\n");
}

// Servers like Hypixel puts all NPCs under UUID version 2.
if (uuids[14] === "2") {
    //Chat.log("§4" + players + " §fwith §4" + uuids);
    FS.open("invalidPlayers.txt").append(players + "\r\n");
    FS.open("invalidUUIDs.txt").append(uuids + "\r\n");
    FS.open("DEBUG.txt").append(players + " (NPC) with " + uuids + " (UUID version 2)" + "\r\n");
}

// Servers like Hypixel puts all nicked players under UUID version 1.
if (uuids[14] === "1") {
    Chat.log("§4" + players + " §fwith §4" + uuids);
    FS.open("invalidPlayers.txt").append(players + "\r\n");
    FS.open("invalidUUIDs.txt").append(uuids + "\r\n");
    FS.open("DEBUG.txt").append(players + " (nicked player) with " + uuids + " (UUID version 1)" + "\r\n");
}
[...]
```

**Comment by Cryptizism** [comment]
oh that's so sick @ItzLevvie thanks for pointing this out!! Didn't even know that laby had a contribution page
