### ISSUE TITLE
Automatically fetch information about set players

### ISSUE THREAD

**Issue by Whitelisted1** [Chit132/abyss-overlay#47]
[Feature Request]
Add a feature to automatically fetch information/stats from other players (such as friends) in order to compare stats

**Comment by Cryptizism** [comment]
@Whitelisted1 I'm not sure what you're requesting... If you do /fl and /gl it should show you all of the stats of your friends (on the pages you show, we can't do all of them because hypixel removed that endpoint) and guild memebers

**Comment by Whitelisted1** [comment]
@Cryptizism thanks for the information, I was unaware of this feature
I was asking for a feature that would allow you to put in some usernames in a text box in the options and have their stats automatically load and display on startup instead of having to be in a game with those specific people, but I guess '/fl' would pretty much work the same way
