### ISSUE TITLE
Feature request: Ratelimit handling

### ISSUE THREAD

**Issue by YHDiamond** [Chit132/abyss-overlay#6]
Right now if your api key gets ratelimited, all the player stat calls made while you're ratelimited show up as nicks. My idea is to handle that 429 error and tell the user that they have been spamming and when they can try again.

**Comment by Cryptizism** [comment]
We don't tend to use this repo as an issue tracker or feature request, whatever. We tend to use the discord which you can find in the overlay by clicking the discord button and find the suggestions channel. However I will forward this to Chit for you this time, thanks.

**Comment by Chit132** [comment]
Gotchu I will keep that in mind for the next update <3 Tysm

**Comment by Cryptizism** [comment]
Has been added to the dev branch, thank you for the suggestion!
